define(
"dojo/cldr/nls/af/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-weekday": "Weeksdag",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, y-M-d",
	"dateFormatItem-MMMEd": "E, MMM d",
	"eraNarrow": [
		"v.C.",
		"n.C."
	],
	"dateFormat-long": "dd MMMM y",
	"months-format-wide": [
		"Januarie",
		"Februarie",
		"Maart",
		"April",
		"Mei",
		"Junie",
		"Julie",
		"Augustus",
		"September",
		"Oktober",
		"November",
		"Desember"
	],
	"dayPeriods-format-wide-pm": "nm.",
	"dateFormat-full": "EEEE dd MMMM y",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "M/d/y",
	"field-era": "Era",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"Januarie",
		"Februarie",
		"Maart",
		"April",
		"Mei",
		"Junie",
		"Julie",
		"Augustus",
		"September",
		"Oktober",
		"November",
		"Desember"
	],
	"timeFormat-short": "h:mm a",
	"quarters-format-wide": [
		"1ste kwartaal",
		"2de kwartaal",
		"3de kwartaal",
		"4de kwartaal"
	],
	"timeFormat-long": "h:mm:ss a z",
	"field-year": "Jaar",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q y",
	"field-hour": "Uur",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Des"
	],
	"timeFormat-full": "h:mm:ss a zzzz",
	"field-day-relative+0": "Vandag",
	"field-day-relative+1": "Môre",
	"field-day-relative+2": "Die dag na môre",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"Mei",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Des"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-standAlone-wide": [
		"1ste kwartaal",
		"2de kwartaal",
		"3de kwartaal",
		"4de kwartaal"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Sondag",
		"Maandag",
		"Dinsdag",
		"Woensdag",
		"Donderdag",
		"Vrydag",
		"Saterdag"
	],
	"dateFormatItem-MMMMd": "MMMM d",
	"timeFormat-medium": "h:mm:ss a",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"eraAbbr": [
		"v.C.",
		"n.C."
	],
	"field-minute": "Minuut",
	"field-dayperiod": "AM/PM",
	"days-standAlone-abbr": [
		"So",
		"Ma",
		"Di",
		"Wo",
		"Do",
		"Vr",
		"Sa"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Gister",
	"field-day-relative+-2": "Die dag voor gister",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "E, M/d",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "Dag",
	"days-format-wide": [
		"Sondag",
		"Maandag",
		"Dinsdag",
		"Woensdag",
		"Donderdag",
		"Vrydag",
		"Saterdag"
	],
	"field-zone": "Tydsone",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-year-relative+-1": "Verlede jaar",
	"field-month-relative+-1": "Verlede maand",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"So",
		"Ma",
		"Di",
		"Wo",
		"Do",
		"Vr",
		"Sa"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"eraNames": [
		"voor Christus",
		"na Christus"
	],
	"days-format-narrow": [
		"S",
		"M",
		"D",
		"W",
		"D",
		"V",
		"S"
	],
	"field-month": "Maand",
	"days-standAlone-narrow": [
		"S",
		"M",
		"D",
		"W",
		"D",
		"V",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "vm.",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormat-short": "yyyy-MM-dd",
	"field-second": "Sekonde",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"field-month-relative+0": "Vandeesmaand",
	"field-month-relative+1": "Volgende maand",
	"field-week": "Week",
	"dateFormat-medium": "dd MMM y",
	"field-year-relative+0": "Hierdie jaar",
	"field-week-relative+-1": "Verlede week",
	"field-year-relative+1": "Volgende jaar",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-week-relative+0": "Vandeesweek",
	"field-week-relative+1": "Volgende week"
}
//end v1.x content
);