define(
"dojo/cldr/nls/uk/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"С",
		"Л",
		"Б",
		"К",
		"Т",
		"Ч",
		"Л",
		"С",
		"В",
		"Ж",
		"Л",
		"Г"
	],
	"field-weekday": "День тижня",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, dd.MM.yyyy",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"до н.е.",
		"н.е."
	],
	"dayPeriods-format-wide-morning": "ранку",
	"dateFormat-long": "d MMMM y 'р'.",
	"months-format-wide": [
		"січня",
		"лютого",
		"березня",
		"квітня",
		"травня",
		"червня",
		"липня",
		"серпня",
		"вересня",
		"жовтня",
		"листопада",
		"грудня"
	],
	"dayPeriods-format-wide-evening": "вечора",
	"dateTimeFormat-medium": "{1} {0}",
	"dayPeriods-format-wide-pm": "пп",
	"dateFormat-full": "EEEE, d MMMM y 'р'.",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-yMd": "dd.MM.yy",
	"field-era": "Ера",
	"dateFormatItem-yM": "MM.yyyy",
	"months-standAlone-wide": [
		"Січень",
		"Лютий",
		"Березень",
		"Квітень",
		"Травень",
		"Червень",
		"Липень",
		"Серпень",
		"Вересень",
		"Жовтень",
		"Листопад",
		"Грудень"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"I квартал",
		"II квартал",
		"III квартал",
		"IV квартал"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Рік",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-yyyyMMMM": "LLLL y",
	"field-hour": "Година",
	"dateFormatItem-MMdd": "dd.MM",
	"months-format-abbr": [
		"січ.",
		"лют.",
		"бер.",
		"квіт.",
		"трав.",
		"черв.",
		"лип.",
		"серп.",
		"вер.",
		"жовт.",
		"лист.",
		"груд."
	],
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "Сьогодні",
	"field-day-relative+1": "Завтра",
	"field-day-relative+2": "Післязавтра",
	"months-standAlone-abbr": [
		"Січ",
		"Лют",
		"Бер",
		"Кві",
		"Тра",
		"Чер",
		"Лип",
		"Сер",
		"Вер",
		"Жов",
		"Лис",
		"Гру"
	],
	"quarters-format-abbr": [
		"I кв.",
		"II кв.",
		"III кв.",
		"IV кв."
	],
	"quarters-standAlone-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Неділя",
		"Понеділок",
		"Вівторок",
		"Середа",
		"Четвер",
		"Пʼятниця",
		"Субота"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-yyMMM": "LLL yy",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"eraAbbr": [
		"до н.е.",
		"н.е."
	],
	"field-minute": "Хвилина",
	"field-dayperiod": "Частина доби",
	"days-standAlone-abbr": [
		"Нд",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dayPeriods-format-wide-night": "ночі",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Вчора",
	"dateTimeFormat-long": "{1} {0}",
	"field-day-relative+-2": "Позавчора",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-yMMMM": "LLLL y",
	"field-day": "День",
	"days-format-wide": [
		"Неділя",
		"Понеділок",
		"Вівторок",
		"Середа",
		"Четвер",
		"Пʼятниця",
		"Субота"
	],
	"field-zone": "Зона",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"С",
		"Л",
		"Б",
		"К",
		"Т",
		"Ч",
		"Л",
		"С",
		"В",
		"Ж",
		"Л",
		"Г"
	],
	"field-year-relative+-1": "Минулого року",
	"field-month-relative+-1": "Минулого місяця",
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"Нд",
		"Пн",
		"Вт",
		"Ср",
		"Чт",
		"Пт",
		"Сб"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"eraNames": [
		"до нашої ери",
		"нашої ери"
	],
	"days-format-narrow": [
		"Н",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"days-standAlone-narrow": [
		"Н",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "Місяць",
	"dateFormatItem-HHmm": "HH:mm",
	"dayPeriods-format-wide-am": "дп",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormat-short": "dd.MM.yy",
	"dayPeriods-format-wide-afternoon": "дня",
	"field-second": "Секунда",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-month-relative+0": "Цього місяця",
	"field-month-relative+1": "Наступного місяця",
	"dateFormatItem-Ed": "E, d",
	"field-week": "Тиждень",
	"dateFormat-medium": "d MMM y",
	"field-year-relative+0": "Цього року",
	"field-week-relative+-1": "Минулого тижня",
	"field-year-relative+1": "Наступного року",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'р'.",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-week-relative+0": "Цього тижня",
	"field-week-relative+1": "Наступного тижня"
}
//end v1.x content
);