define(
"dojo/cldr/nls/fa/hebrew", //begin v1.x content
{
	"dateFormatItem-yM": "y/M",
	"dateFormatItem-yQ": "Q y",
	"months-standAlone-abbr-leap": "واذار الثانی",
	"dayPeriods-format-wide-pm": "بعدازظهر",
	"dateFormatItem-MMMEd": "E d LLL",
	"dateTimeFormat-full": "{1}، ساعت {0}",
	"dateFormatItem-yQQQ": "QQQ y",
	"days-standAlone-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"months-standAlone-narrow": [
		"ت",
		"ح",
		"ک",
		"ط",
		"ش",
		"آ",
		"و",
		"ن",
		"ا",
		"س",
		"ت",
		"آ",
		"ا"
	],
	"dateTimeFormat-short": "{1}، {0}",
	"dayPeriods-format-wide-am": "قبلازظهر",
	"months-format-narrow-leap": "و",
	"dateTimeFormat-medium": "{1}، {0}",
	"months-format-abbr-leap": "واذار الثانی",
	"quarters-standAlone-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"timeFormat-full": "H:mm:ss (zzzz)",
	"months-standAlone-narrow-leap": "و",
	"months-standAlone-abbr": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-yMMM": "MMM y",
	"days-standAlone-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormat-long": "d MMMM y",
	"timeFormat-medium": "H:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"dateFormat-medium": "d MMM y",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-yMd": "y/M/d",
	"quarters-standAlone-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"quarters-standAlone-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"dateTimeFormat-long": "{1}، ساعت {0}",
	"months-standAlone-wide": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"dateFormatItem-MMMd": "d LLL",
	"quarters-format-narrow": [
		"۱",
		"۲",
		"۳",
		"۴"
	],
	"timeFormat-long": "H:mm:ss (z)",
	"months-format-abbr": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"dateFormatItem-H": "H",
	"timeFormat-short": "H:mm",
	"quarters-format-abbr": [
		"سم۱",
		"سم۲",
		"سم۳",
		"سم۴"
	],
	"days-format-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"days-format-narrow": [
		"ی",
		"د",
		"س",
		"چ",
		"پ",
		"ج",
		"ش"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-MEd": "E M/d",
	"dateTimeFormats-appendItem-Day-Of-Week": "{1} {0}",
	"months-format-narrow": [
		"ت",
		"ح",
		"ک",
		"ط",
		"ش",
		"آ",
		"و",
		"ن",
		"ا",
		"س",
		"ت",
		"آ",
		"ا"
	],
	"days-standAlone-abbr": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	],
	"months-standAlone-wide-leap": "واذار الثانی",
	"dateFormat-short": "yyyy/M/d",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMEd": "E y/M/d",
	"months-format-wide": [
		"تشری",
		"حشوان",
		"کسلو",
		"طوت",
		"شباط",
		"آذار",
		"واذار",
		"نیسان",
		"ایار",
		"سیوان",
		"تموز",
		"آب",
		"ایلول"
	],
	"quarters-format-wide": [
		"سهماههٔ اول",
		"سهماههٔ دوم",
		"سهماههٔ سوم",
		"سهماههٔ چهارم"
	],
	"months-format-wide-leap": "واذار الثانی",
	"days-format-wide": [
		"یکشنبه",
		"دوشنبه",
		"سهشنبه",
		"چهارشنبه",
		"پنجشنبه",
		"جمعه",
		"شنبه"
	]
}
//end v1.x content
);