define(
"dojo/cldr/nls/hr/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4.",
		"5.",
		"6.",
		"7.",
		"8.",
		"9.",
		"10.",
		"11.",
		"12."
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-weekday": "dan u tjednu",
	"dateFormatItem-yyQQQQ": "QQQQ yy.",
	"dateFormatItem-yQQQ": "QQQ y.",
	"dateFormatItem-yyMMMEd": "E, d. MMM yy.",
	"dateFormatItem-yMEd": "E, d. M. y.",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"eraNarrow": [
		"pr.n.e.",
		"AD"
	],
	"dateFormat-long": "d. MMMM y.",
	"months-format-wide": [
		"siječnja",
		"veljače",
		"ožujka",
		"travnja",
		"svibnja",
		"lipnja",
		"srpnja",
		"kolovoza",
		"rujna",
		"listopada",
		"studenoga",
		"prosinca"
	],
	"dayPeriods-format-wide-pm": "PM",
	"dateFormat-full": "EEEE, d. MMMM y.",
	"dateFormatItem-Md": "d. M.",
	"dayPeriods-format-wide-noon": "podne",
	"dateFormatItem-yMd": "d. M. y.",
	"field-era": "era",
	"dateFormatItem-yM": "M. yyyy.",
	"months-standAlone-wide": [
		"siječanj",
		"veljača",
		"ožujak",
		"travanj",
		"svibanj",
		"lipanj",
		"srpanj",
		"kolovoz",
		"rujan",
		"listopad",
		"studeni",
		"prosinac"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "godina",
	"dateFormatItem-yMMM": "LLL y.",
	"dateFormatItem-yQ": "Q. yyyy.",
	"dateFormatItem-yyyyMMMM": "LLLL y.",
	"dateFormatItem-MMdd": "dd. MM.",
	"field-hour": "sat",
	"months-format-abbr": [
		"sij",
		"velj",
		"ožu",
		"tra",
		"svi",
		"lip",
		"srp",
		"kol",
		"ruj",
		"lis",
		"stu",
		"pro"
	],
	"dateFormatItem-yyQ": "Q yy.",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"dateFormatItem-H": "HH",
	"months-standAlone-abbr": [
		"sij",
		"velj",
		"ožu",
		"tra",
		"svi",
		"lip",
		"srp",
		"kol",
		"ruj",
		"lis",
		"stu",
		"pro"
	],
	"quarters-format-abbr": [
		"1kv",
		"2kv",
		"3kv",
		"4kv"
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dateFormatItem-M": "L.",
	"days-standAlone-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"dayPeriods-format-abbr-noon": "podne",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"1kv",
		"2kv",
		"3kv",
		"4kv"
	],
	"eraAbbr": [
		"p. n. e.",
		"A. D."
	],
	"field-minute": "minuta",
	"field-dayperiod": "dio dana",
	"days-standAlone-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"dateFormatItem-d": "d.",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-day-relative+-1": "jučer",
	"dateFormatItem-h": "hh a",
	"field-day-relative+-2": "prekjučer",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d. M.",
	"dateFormatItem-yMMMM": "LLLL y.",
	"field-day": "dan",
	"days-format-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"field-zone": "zona",
	"dateFormatItem-yyyyMM": "MM. yyyy.",
	"dateFormatItem-y": "y.",
	"months-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4.",
		"5.",
		"6.",
		"7.",
		"8.",
		"9.",
		"10.",
		"11.",
		"12."
	],
	"field-year-relative+-1": "Prošla godina",
	"field-month-relative+-1": "Prošli mjesec",
	"dateFormatItem-hm": "hh:mm a",
	"days-format-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"dateFormatItem-yMMMd": "d. MMM y.",
	"eraNames": [
		"Prije Krista",
		"Poslije Krista"
	],
	"days-format-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Č",
		"P",
		"S"
	],
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"dateFormatItem-MMM": "LLL",
	"field-month": "mjesec",
	"dayPeriods-format-wide-am": "AM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormat-short": "d.M.y.",
	"dayPeriods-format-narrow-noon": "n",
	"field-second": "sekunda",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"field-month-relative+0": "Ovaj mjesec",
	"field-month-relative+1": "Sljedeći mjesec",
	"dateFormatItem-Ed": "E, d.",
	"field-week": "tjedan",
	"dateFormat-medium": "d. M. y.",
	"field-year-relative+0": "Ova godina",
	"field-week-relative+-1": "Prošli tjedan",
	"field-year-relative+1": "Sljedeća godina",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "hh:mm:ss a",
	"field-week-relative+0": "Ovaj tjedan",
	"field-week-relative+1": "Sljedeći tjedan"
}
//end v1.x content
);