define(
"dojo/cldr/nls/sr/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-weekday": "дан у недељи",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yQQQ": "QQQ. y",
	"dateFormatItem-yMEd": "E, d. M. yyyy.",
	"dateFormatItem-MMMEd": "E d. MMM",
	"eraNarrow": [
		"п.н.е.",
		"н.е."
	],
	"dateFormatItem-MMMdd": "dd.MMM",
	"dateFormat-long": "dd. MMMM y.",
	"months-format-wide": [
		"јануар",
		"фебруар",
		"март",
		"април",
		"мај",
		"јун",
		"јул",
		"август",
		"септембар",
		"октобар",
		"новембар",
		"децембар"
	],
	"dayPeriods-format-wide-pm": "поподне",
	"dateFormat-full": "EEEE, dd. MMMM y.",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyMMdd": "dd.MM.yy",
	"dateFormatItem-yMd": "d. M. y.",
	"field-era": "ера",
	"dateFormatItem-yM": "y-M",
	"months-standAlone-wide": [
		"јануар",
		"фебруар",
		"март",
		"април",
		"мај",
		"јун",
		"јул",
		"август",
		"септембар",
		"октобар",
		"новембар",
		"децембар"
	],
	"timeFormat-short": "HH.mm",
	"quarters-format-wide": [
		"Прво тромесечје",
		"Друго тромесечје",
		"Треће тромесечје",
		"Четврто тромесечје"
	],
	"timeFormat-long": "HH.mm.ss z",
	"field-year": "година",
	"dateFormatItem-yMMM": "MMM y.",
	"dateFormatItem-yQ": "y Q",
	"dateFormatItem-yyyyMMMM": "MMMM y.",
	"field-hour": "час",
	"dateFormatItem-MMdd": "MM-dd",
	"months-format-abbr": [
		"јан",
		"феб",
		"мар",
		"апр",
		"мај",
		"јун",
		"јул",
		"авг",
		"сеп",
		"окт",
		"нов",
		"дец"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH.mm.ss zzzz",
	"field-day-relative+0": "данас",
	"field-day-relative+1": "сутра",
	"field-day-relative+2": "прекосутра",
	"months-standAlone-abbr": [
		"јан",
		"феб",
		"мар",
		"апр",
		"мај",
		"јун",
		"јул",
		"авг",
		"сеп",
		"окт",
		"нов",
		"дец"
	],
	"quarters-format-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"quarters-standAlone-wide": [
		"Прво тромесечје",
		"Друго тромесечје",
		"Треће тромесечје",
		"Четврто тромесечје"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"timeFormat-medium": "HH.mm.ss",
	"dateFormatItem-Hm": "HH.mm",
	"quarters-standAlone-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"eraAbbr": [
		"п. н. е.",
		"н. е."
	],
	"field-minute": "минут",
	"field-dayperiod": "пре подне/поподне",
	"days-standAlone-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"dateFormatItem-yyMMMd": "d. MMM yy.",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm.ss",
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"field-day-relative+-1": "јуче",
	"dateFormatItem-h": "hh a",
	"field-day-relative+-2": "прекјуче",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-yMMMM": "MMMM y.",
	"field-day": "дан",
	"days-format-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"field-zone": "зона",
	"dateFormatItem-yyyyMM": "yyyy-MM",
	"dateFormatItem-y": "y.",
	"months-standAlone-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"field-year-relative+-1": "Прошле године",
	"field-month-relative+-1": "Прошлог месеца",
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormatItem-hm": "hh.mm a",
	"days-format-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"dateFormatItem-yMMMd": "d. MMM y.",
	"eraNames": [
		"Пре нове ере",
		"Нове ере"
	],
	"days-format-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"field-month": "месец",
	"days-standAlone-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "пре подне",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormat-short": "d.M.yy.",
	"field-second": "секунд",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"field-month-relative+0": "Овог месеца",
	"field-month-relative+1": "Следећег месеца",
	"dateFormatItem-Ed": "E d.",
	"field-week": "недеља",
	"dateFormat-medium": "dd.MM.y.",
	"field-year-relative+0": "Ове године",
	"field-week-relative+-1": "Прошле недеље",
	"field-year-relative+1": "Следеће године",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-hms": "hh.mm.ss a",
	"dateFormatItem-yyyy": "y.",
	"field-week-relative+0": "Ове недеље",
	"field-week-relative+1": "Следеће недеље"
}
//end v1.x content
);