define(
"dojo/cldr/nls/kn/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"ಜ",
		"ಫೆ",
		"ಮಾ",
		"ಎ",
		"ಮೇ",
		"ಜೂ",
		"ಜು",
		"ಆ",
		"ಸೆ",
		"ಅ",
		"ನ",
		"ಡಿ"
	],
	"field-weekday": "ವಾರದ ದಿನ",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E,d/M/y",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"ಕ್ರಿ.ಪೂ",
		"ಜಾಹೀ"
	],
	"dateFormat-long": "d MMMM y",
	"months-format-wide": [
		"ಜನವರೀ",
		"ಫೆಬ್ರವರೀ",
		"ಮಾರ್ಚ್",
		"ಎಪ್ರಿಲ್",
		"ಮೆ",
		"ಜೂನ್",
		"ಜುಲೈ",
		"ಆಗಸ್ಟ್",
		"ಸಪ್ಟೆಂಬರ್",
		"ಅಕ್ಟೋಬರ್",
		"ನವೆಂಬರ್",
		"ಡಿಸೆಂಬರ್"
	],
	"dayPeriods-format-wide-pm": "PM",
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormatItem-Md": "d/M",
	"dayPeriods-format-abbr-am": "AM",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "ಯುಗ",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"ಜನವರೀ",
		"ಫೆಬ್ರವರೀ",
		"ಮಾರ್ಚ್",
		"ಎಪ್ರಿಲ್",
		"ಮೆ",
		"ಜೂನ್",
		"ಜುಲೈ",
		"ಆಗಸ್ಟ್",
		"ಸಪ್ಟೆಂಬರ್",
		"ಅಕ್ಟೋಬರ್",
		"ನವೆಂಬರ್",
		"ಡಿಸೆಂಬರ್"
	],
	"timeFormat-short": "hh:mm a",
	"quarters-format-wide": [
		"ಒಂದು 1",
		"ಎರಡು 2",
		"ಮೂರು 3",
		"ನಾಲೃಕ 4"
	],
	"timeFormat-long": "hh:mm:ss a z",
	"field-year": "ವರ್ಷ",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q y",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-hour": "ಗಂಟೆ",
	"dateFormatItem-MMdd": "dd-MM",
	"months-format-abbr": [
		"ಜನವರೀ",
		"ಫೆಬ್ರವರೀ",
		"ಮಾರ್ಚ್",
		"ಎಪ್ರಿಲ್",
		"ಮೆ",
		"ಜೂನ್",
		"ಜುಲೈ",
		"ಆಗಸ್ಟ್",
		"ಸಪ್ಟೆಂಬರ್",
		"ಅಕ್ಟೋಬರ್",
		"ನವೆಂಬರ್",
		"ಡಿಸೆಂಬರ್"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "hh:mm:ss a zzzz",
	"field-day-relative+0": "ಇಂದು",
	"field-day-relative+1": "ನಾಳೆ",
	"field-day-relative+2": "ನಾಡಿದ್ದು",
	"months-standAlone-abbr": [
		"ಜನವರೀ",
		"ಫೆಬ್ರವರೀ",
		"ಮಾರ್ಚ್",
		"ಎಪ್ರಿಲ್",
		"ಮೆ",
		"ಜೂನ್",
		"ಜುಲೈ",
		"ಆಗಸ್ಟ್",
		"ಸಪ್ಟೆಂಬರ್",
		"ಅಕ್ಟೋಬರ್",
		"ನವೆಂಬರ್",
		"ಡಿಸೆಂಬರ್"
	],
	"quarters-format-abbr": [
		"ಒಂದು 1",
		"ಎರಡು 2",
		"ಮೂರು 3",
		"ನಾಲೃಕ 4"
	],
	"quarters-standAlone-wide": [
		"ಒಂದು 1",
		"ಎರಡು 2",
		"ಮೂರು 3",
		"ನಾಲೃಕ 4"
	],
	"days-standAlone-wide": [
		"ರವಿವಾರ",
		"ಸೋಮವಾರ",
		"ಮಂಗಳವಾರ",
		"ಬುಧವಾರ",
		"ಗುರುವಾರ",
		"ಶುಕ್ರವಾರ",
		"ಶನಿವಾರ"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"timeFormat-medium": "hh:mm:ss a",
	"quarters-standAlone-abbr": [
		"ಒಂದು 1",
		"ಎರಡು 2",
		"ಮೂರು 3",
		"ನಾಲೃಕ 4"
	],
	"eraAbbr": [
		"ಕ್ರಿ.ಪೂ",
		"ಜಾಹೀ"
	],
	"field-minute": "ನಿಮಿಷ",
	"field-dayperiod": "ಪೂರ್ವಾಹ್ನ/ಅಪರಾಹ್ನ",
	"days-standAlone-abbr": [
		"ರ.",
		"ಸೋ.",
		"ಮಂ.",
		"ಬು.",
		"ಗು.",
		"ಶು.",
		"ಶನಿ."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "ನಿನ್ನೆ",
	"dayPeriods-format-narrow-am": "ಪೂರ್ವಾಹ್ನ",
	"field-day-relative+-2": "ಮೊನ್ನೆ",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"field-day": "ದಿನ",
	"days-format-wide": [
		"ರವಿವಾರ",
		"ಸೋಮವಾರ",
		"ಮಂಗಳವಾರ",
		"ಬುಧವಾರ",
		"ಗುರುವಾರ",
		"ಶುಕ್ರವಾರ",
		"ಶನಿವಾರ"
	],
	"field-zone": "ಸಮಯ ವಲಯ:",
	"dateFormatItem-yyyyMM": "MM-yyyy",
	"months-standAlone-narrow": [
		"ಜ",
		"ಫೆ",
		"ಮಾ",
		"ಎ",
		"ಮೇ",
		"ಜೂ",
		"ಜು",
		"ಆ",
		"ಸೆ",
		"ಅ",
		"ನ",
		"ಡಿ"
	],
	"field-year-relative+-1": "ಕೊನೆಯ ವರ್ಷ",
	"field-month-relative+-1": "ಕಳೆದ ತಿಂಗಳು",
	"dayPeriods-format-abbr-pm": "PM",
	"days-format-abbr": [
		"ರ.",
		"ಸೋ.",
		"ಮಂ.",
		"ಬು.",
		"ಗು.",
		"ಶು.",
		"ಶನಿ."
	],
	"dateFormatItem-yMMMd": "d, MMM, y",
	"eraNames": [
		"ಈಸಪೂವ೯.",
		"ಕ್ರಿಸ್ತ ಶಕ"
	],
	"days-format-narrow": [
		"ರ",
		"ಸೋ",
		"ಮಂ",
		"ಬು",
		"ಗು",
		"ಶು",
		"ಶ"
	],
	"field-month": "ತಿಂಗಳು",
	"days-standAlone-narrow": [
		"ರ",
		"ಸೋ",
		"ಮಂ",
		"ಬು",
		"ಗು",
		"ಶು",
		"ಶ"
	],
	"dayPeriods-format-wide-am": "AM",
	"dateFormat-short": "d-M-yy",
	"field-second": "ಸೆಕೆಂಡ್",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"field-month-relative+0": "ಈ ತಿಂಗಳು",
	"field-month-relative+1": "ಮುಂದಿನ ತಿಂಗಳು",
	"field-week": "ವಾರ",
	"dateFormat-medium": "d MMM y",
	"field-year-relative+0": "ಈ ವರ್ಷ",
	"field-week-relative+-1": "ಕೊನೆಯ ವಾರ",
	"field-year-relative+1": "ಮುಂದಿನ ವರ್ಷ",
	"dayPeriods-format-narrow-pm": "ಅಪ.",
	"field-week-relative+0": "ಈ ವಾರ",
	"field-week-relative+1": "ಮುಂದಿನ ವಾರ"
}
//end v1.x content
);