define(
"dojo/cldr/nls/mr/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"जा",
		"फे",
		"मा",
		"ए",
		"मे",
		"जू",
		"जु",
		"ऑ",
		"स",
		"ऑ",
		"नो",
		"डि"
	],
	"field-weekday": "आठवड्याचा दिवस",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"ईसापूर्व",
		"सन"
	],
	"dateFormat-long": "d MMMM y",
	"months-format-wide": [
		"जानेवारी",
		"फेब्रुवारी",
		"मार्च",
		"एप्रिल",
		"मे",
		"जून",
		"जुलै",
		"ऑगस्ट",
		"सप्टेंबर",
		"ऑक्टोबर",
		"नोव्हेंबर",
		"डिसेंबर"
	],
	"dayPeriods-format-wide-pm": "म.नं.",
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormatItem-Md": "d/M",
	"dayPeriods-format-abbr-am": "AM",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "युग",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"जानेवारी",
		"फेब्रुवारी",
		"मार्च",
		"एप्रिल",
		"मे",
		"जून",
		"जुलै",
		"ऑगस्ट",
		"सप्टेंबर",
		"ऑक्टोबर",
		"नोव्हेंबर",
		"डिसेंबर"
	],
	"timeFormat-short": "h-mm a",
	"quarters-format-wide": [
		"प्रथम तिमाही",
		"द्वितीय तिमाही",
		"तृतीय तिमाही",
		"चतुर्थ तिमाही"
	],
	"timeFormat-long": "h-mm-ss a z",
	"field-year": "वर्ष",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q y",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-hour": "तास",
	"dateFormatItem-MMdd": "dd-MM",
	"months-format-abbr": [
		"जाने",
		"फेब्रु",
		"मार्च",
		"एप्रि",
		"मे",
		"जून",
		"जुलै",
		"ऑग",
		"सेप्टें",
		"ऑक्टोबर",
		"नोव्हें",
		"डिसें"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "h-mm-ss a zzzz",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "उद्या",
	"field-day-relative+2": "परवा",
	"months-standAlone-abbr": [
		"जाने",
		"फेब्रु",
		"मार्च",
		"एप्रि",
		"मे",
		"जून",
		"जुलै",
		"ऑग",
		"सेप्टें",
		"ऑक्टोबर",
		"नोव्हें",
		"डिसें"
	],
	"quarters-format-abbr": [
		"ति 1",
		"2 री तिमाही",
		"ति 3",
		"ति 4"
	],
	"quarters-standAlone-wide": [
		"प्रथम तिमाही",
		"द्वितीय तिमाही",
		"तृतीय तिमाही",
		"चतुर्थ तिमाही"
	],
	"dateFormatItem-M": "M",
	"days-standAlone-wide": [
		"रविवार",
		"सोमवार",
		"मंगळवार",
		"बुधवार",
		"गुरुवार",
		"शुक्रवार",
		"शनिवार"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"timeFormat-medium": "h-mm-ss a",
	"dateFormatItem-Hm": "H-mm",
	"quarters-standAlone-abbr": [
		"ति 1",
		"ति 2",
		"ति 3",
		"ति 4"
	],
	"eraAbbr": [
		"ईसापूर्व",
		"सन"
	],
	"field-minute": "मिनिट",
	"field-dayperiod": "AM/PM",
	"days-standAlone-abbr": [
		"रवि",
		"सोम",
		"मंगळ",
		"बुध",
		"गुरु",
		"शुक्र",
		"शनि"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "काल",
	"dayPeriods-format-narrow-am": "a",
	"field-day-relative+-2": "परवा",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d/M",
	"field-day": "दिवस",
	"days-format-wide": [
		"रविवार",
		"सोमवार",
		"मंगळवार",
		"बुधवार",
		"गुरुवार",
		"शुक्रवार",
		"शनिवार"
	],
	"field-zone": "झोन",
	"dateFormatItem-yyyyMM": "MM-yyyy",
	"months-standAlone-narrow": [
		"जा",
		"फे",
		"मा",
		"ए",
		"मे",
		"जू",
		"जु",
		"ऑ",
		"स",
		"ऑ",
		"नो",
		"डि"
	],
	"field-year-relative+-1": "मागील वर्ष",
	"field-month-relative+-1": "मागील महिना",
	"dayPeriods-format-abbr-pm": "PM",
	"days-format-abbr": [
		"रवि",
		"सोम",
		"मंगळ",
		"बुध",
		"गुरु",
		"शुक्र",
		"शनि"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"eraNames": [
		"ईसवीसनपूर्व",
		"ईसवीसन"
	],
	"days-format-narrow": [
		"र",
		"सो",
		"मं",
		"बु",
		"गु",
		"शु",
		"श"
	],
	"field-month": "महिना",
	"days-standAlone-narrow": [
		"र",
		"सो",
		"मं",
		"बु",
		"गु",
		"शु",
		"श"
	],
	"dayPeriods-format-wide-am": "म.पू.",
	"dateFormat-short": "d-M-yy",
	"field-second": "सेकंद",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-month-relative+0": "हा महिना",
	"field-month-relative+1": "पुढील महिना",
	"dateFormatItem-Ed": "E d",
	"field-week": "आठव़डा",
	"dateFormat-medium": "d MMM y",
	"field-year-relative+0": "या वर्षी",
	"field-week-relative+-1": "मागील आठवडा",
	"field-year-relative+1": "पुढील वर्ष",
	"dayPeriods-format-narrow-pm": "p",
	"dateFormatItem-Hms": "H-mm-ss",
	"field-week-relative+0": "हा आठवडा",
	"field-week-relative+1": "पुढील आठवडा"
}
//end v1.x content
);