define(
"dojo/cldr/nls/sr-latn/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"field-weekday": "dan u nedelji",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yMEd": "E, d. M. yyyy.",
	"dateFormatItem-MMMEd": "E d. MMM",
	"eraNarrow": [
		"p. n. e.",
		"n. e"
	],
	"dateFormatItem-MMMdd": "dd.MMM",
	"dateFormat-long": "dd. MMMM y.",
	"months-format-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"dayPeriods-format-wide-pm": "popodne",
	"dateFormat-full": "EEEE, dd. MMMM y.",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yyMMdd": "dd.MM.yy",
	"dateFormatItem-yMd": "d. M. y.",
	"field-era": "era",
	"dateFormatItem-yM": "y-M",
	"months-standAlone-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"jun",
		"jul",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"timeFormat-short": "HH.mm",
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"timeFormat-long": "HH.mm.ss z",
	"field-year": "godina",
	"dateFormatItem-yMMM": "MMM y.",
	"dateFormatItem-yQ": "y Q",
	"dateFormatItem-yyyyMMMM": "MMMM y.",
	"field-hour": "čas",
	"dateFormatItem-MMdd": "MM-dd",
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"avg",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH.mm.ss zzzz",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"avg",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"timeFormat-medium": "HH.mm.ss",
	"dateFormatItem-Hm": "HH.mm",
	"eraAbbr": [
		"p. n. e.",
		"n. e"
	],
	"field-minute": "minut",
	"field-dayperiod": "pre podne/ popodne",
	"days-standAlone-abbr": [
		"ned",
		"pon",
		"uto",
		"sre",
		"čet",
		"pet",
		"sub"
	],
	"dateFormatItem-yyMMMd": "d. MMM yy.",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm.ss",
	"field-day-relative+-1": "juče",
	"dateFormatItem-h": "hh a",
	"field-day-relative+-2": "prekjuče",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-yMMMM": "MMMM y.",
	"field-day": "dan",
	"days-format-wide": [
		"nedelja",
		"ponedeljak",
		"utorak",
		"sreda",
		"četvrtak",
		"petak",
		"subota"
	],
	"field-zone": "zona",
	"dateFormatItem-yyyyMM": "yyyy-MM",
	"dateFormatItem-y": "y.",
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormatItem-hm": "hh.mm a",
	"days-format-abbr": [
		"ned",
		"pon",
		"uto",
		"sre",
		"čet",
		"pet",
		"sub"
	],
	"dateFormatItem-yMMMd": "d. MMM y.",
	"eraNames": [
		"Pre nove ere",
		"Nove ere"
	],
	"days-format-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"field-month": "mesec",
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "pre podne",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormat-short": "d.M.yy.",
	"field-second": "sekund",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"dateFormatItem-Ed": "E d.",
	"field-week": "nedelja",
	"dateFormat-medium": "dd.MM.y.",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-hms": "hh.mm.ss a",
	"dateFormatItem-yyyy": "y."
}
//end v1.x content
);