define(
"dojo/cldr/nls/fil/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"E",
		"P",
		"M",
		"A",
		"M",
		"H",
		"H",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-weekday": "Araw ng Linggo",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yMEd": "E, yyyy-M-d",
	"dateFormatItem-MMMEd": "E MMM d",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormat-long": "MMMM d, y",
	"months-format-wide": [
		"Enero",
		"Pebrero",
		"Marso",
		"Abril",
		"Mayo",
		"Hunyo",
		"Hulyo",
		"Agosto",
		"Setyembre",
		"Oktubre",
		"Nobyembre",
		"Disyembre"
	],
	"dateFormat-full": "EEEE, MMMM dd y",
	"dateFormatItem-Md": "M-d",
	"dayPeriods-format-abbr-am": "AM",
	"dateFormatItem-yMd": "M/d/y",
	"field-era": "Era",
	"dateFormatItem-yM": "yyyy-M",
	"months-standAlone-wide": [
		"Enero",
		"Pebrero",
		"Marso",
		"Abril",
		"Mayo",
		"Hunyo",
		"Hulyo",
		"Agosto",
		"Setyembre",
		"Oktubre",
		"Nobyembre",
		"Disyembre"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"ika-1 sangkapat",
		"ika-2 sangkapat",
		"ika-3 quarter",
		"ika-4 na quarter"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Taon",
	"dateFormatItem-yMMM": "y MMM",
	"dateFormatItem-yQ": "Q y",
	"field-hour": "Oras",
	"months-format-abbr": [
		"Ene",
		"Peb",
		"Mar",
		"Abr",
		"May",
		"Hun",
		"Hul",
		"Ago",
		"Set",
		"Okt",
		"Nob",
		"Dis"
	],
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "Today",
	"field-day-relative+1": "Tomorrow",
	"field-day-relative+2": "Araw pagkatapos ng kahapon",
	"months-standAlone-abbr": [
		"Ene",
		"Peb",
		"Mar",
		"Abr",
		"May",
		"Hun",
		"Hul",
		"Ago",
		"Set",
		"Okt",
		"Nob",
		"Dis"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"ika-1 sangkapat",
		"ika-2 quarter",
		"ika-3 sangkapat",
		"ika-4 na quarter"
	],
	"days-standAlone-wide": [
		"Linggo",
		"Lunes",
		"Martes",
		"Miyerkules",
		"Huwebes",
		"Biyernes",
		"Sabado"
	],
	"dateFormatItem-MMMMd": "MMMM d",
	"dateFormatItem-yyMMM": "MMM yy",
	"timeFormat-medium": "HH:mm:ss",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"BC",
		"AD"
	],
	"field-minute": "Minuto",
	"field-dayperiod": "Dayperiod",
	"days-standAlone-abbr": [
		"Lin",
		"Lun",
		"Mar",
		"Miy",
		"Huw",
		"Biy",
		"Sab"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Yesterday",
	"dayPeriods-format-narrow-am": "a",
	"field-day-relative+-2": "Araw bago ang kahapon",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "E, M-d",
	"dateFormatItem-yMMMM": "y MMMM",
	"field-day": "Araw",
	"days-format-wide": [
		"Linggo",
		"Lunes",
		"Martes",
		"Miyerkules",
		"Huwebes",
		"Biyernes",
		"Sabado"
	],
	"field-zone": "Zone",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"E",
		"P",
		"M",
		"A",
		"M",
		"H",
		"H",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-year-relative+-1": "Nakaraang taon",
	"field-month-relative+-1": "Nakaraang buwan",
	"dateFormatItem-yyMM": "yy-MM",
	"dayPeriods-format-abbr-pm": "PM",
	"days-format-abbr": [
		"Lin",
		"Lun",
		"Mar",
		"Mye",
		"Huw",
		"Bye",
		"Sab"
	],
	"dateFormatItem-yMMMd": "MMM d, y",
	"eraNames": [
		"BC",
		"AD"
	],
	"days-format-narrow": [
		"L",
		"L",
		"M",
		"M",
		"H",
		"B",
		"S"
	],
	"field-month": "Buwan",
	"days-standAlone-narrow": [
		"L",
		"L",
		"M",
		"M",
		"H",
		"B",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMMEd": "E MMMM d",
	"dateFormat-short": "M/d/yy",
	"field-second": "Segundo",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"field-month-relative+0": "Ngayon buwang ito",
	"field-month-relative+1": "Susunod na buwan",
	"field-week": "Linggo",
	"dateFormat-medium": "MMM d, y",
	"field-year-relative+0": "Sa taong ito",
	"field-week-relative+-1": "Nakaraang Linggo",
	"field-year-relative+1": "Susunod na taon",
	"dayPeriods-format-narrow-pm": "p",
	"field-week-relative+0": "Sa linggong ito",
	"field-week-relative+1": "Susunod na linggo"
}
//end v1.x content
);