define(
"dojo/cldr/nls/vi/islamic", //begin v1.x content
{
	"dateFormatItem-yM": "M/yyyy",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-yQ": "Q yyyy",
	"dayPeriods-format-wide-pm": "CH",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateTimeFormat-full": "{0} {1}",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-MMM": "LLL",
	"dateTimeFormat-short": "{0} {1}",
	"dayPeriods-format-wide-am": "SA",
	"dateTimeFormat-medium": "{0} {1}",
	"dateFormatItem-y": "y",
	"dateFormatItem-yyyy": "'Năm' y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-yMMM": "MMM y",
	"days-standAlone-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormatItem-yyyyMM": "MM-y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d/M/y",
	"quarters-standAlone-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-ms": "mm:ss",
	"dateTimeFormat-long": "{0} {1}",
	"dateFormatItem-yyyyMd": "d-M-y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-yyyyMEd": "E, d-M-y G",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-yyQ": "Q yy G",
	"dateFormatItem-H": "HH",
	"dateFormatItem-MMMMd": "d MMMM",
	"days-format-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-M": "L",
	"days-format-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"dateFormatItem-yMMMd": "d MMM, y",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-hm": "h:mm a",
	"dateFormat-short": "dd/MM/y G",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormat-full": "EEEE, 'ngày' dd MMMM 'năm' y G",
	"dateFormatItem-Md": "d-M",
	"dateFormatItem-yMEd": "E, d-M-yyyy",
	"dateFormatItem-yyyyQ": "Q y G",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-d": "'Ngày' d",
	"quarters-format-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"days-format-wide": [
		"Chủ nhật",
		"Thứ hai",
		"Thứ ba",
		"Thứ tư",
		"Thứ năm",
		"Thứ sáu",
		"Thứ bảy"
	],
	"dateFormatItem-h": "h a"
}
//end v1.x content
);