define(
"dojo/cldr/nls/nn/gregorian", //begin v1.x content
{
	"dateFormatItem-yM": "M y",
	"field-dayperiod": "f.m./e.m.-val",
	"dateFormatItem-yQ": "Q y",
	"dayPeriods-format-wide-pm": "ettermiddag",
	"field-minute": "minutt",
	"eraNames": [
		"f.Kr.",
		"e.Kr."
	],
	"dateFormatItem-MMMEd": "E d. MMM",
	"field-day-relative+-1": "i går",
	"field-weekday": "vekedag",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-day-relative+-2": "i forgårs",
	"dateFormatItem-MMdd": "dd.MM",
	"days-standAlone-wide": [
		"søndag",
		"måndag",
		"tysdag",
		"onsdag",
		"torsdag",
		"fredag",
		"laurdag"
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-era": "æra",
	"field-hour": "time",
	"dayPeriods-format-wide-am": "formiddag",
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"timeFormat-full": "'kl'. HH:mm:ss zzzz",
	"months-standAlone-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"mai",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"des."
	],
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-yMMM": "MMM y",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgon",
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"field-day-relative+2": "i overmorgon",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "d. MMMM y",
	"timeFormat-medium": "HH:mm:ss",
	"field-zone": "sone",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-yyMM": "MM.yy",
	"dateFormat-medium": "d. MMM y",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-yMd": "d.M.yyyy",
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dateFormatItem-ms": "mm:ss",
	"field-year": "år",
	"field-week": "veke",
	"months-standAlone-wide": [
		"januar",
		"februar",
		"mars",
		"april",
		"mai",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"desember"
	],
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-long": "HH:mm:ss z",
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"mai",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"des."
	],
	"timeFormat-short": "HH:mm",
	"field-month": "månad",
	"dateFormatItem-MMMMd": "d. MMMM",
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"days-format-abbr": [
		"sø.",
		"må.",
		"ty.",
		"on.",
		"to.",
		"fr.",
		"la."
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"dateFormatItem-yMMMd": "d. MMM y",
	"field-second": "sekund",
	"field-day": "dag",
	"dateFormatItem-MEd": "E d.M",
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dateFormatItem-hm": "h:mm a",
	"days-standAlone-abbr": [
		"sø.",
		"må.",
		"ty.",
		"on.",
		"to.",
		"fr.",
		"la."
	],
	"dateFormat-short": "dd.MM.yy",
	"dateFormatItem-yMMMEd": "E d. MMM y",
	"dateFormat-full": "EEEE d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yMEd": "E d.M.yyyy",
	"months-format-wide": [
		"januar",
		"februar",
		"mars",
		"april",
		"mai",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"desember"
	],
	"dateFormatItem-d": "d.",
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"days-format-wide": [
		"søndag",
		"måndag",
		"tysdag",
		"onsdag",
		"torsdag",
		"fredag",
		"laurdag"
	],
	"eraNarrow": [
		"f.Kr.",
		"e.Kr."
	]
}
//end v1.x content
);