define(
"dojo/cldr/nls/kea/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-weekday": "Dia di simana",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yyMMMEd": "E, d 'de' MMM 'de' yy",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dateFormatItem-MMMEd": "E, d MMM",
	"eraNarrow": [
		"AK",
		"DK"
	],
	"dateFormat-long": "d 'di' MMMM 'di' y",
	"months-format-wide": [
		"Janeru",
		"Fevereru",
		"Marsu",
		"Abril",
		"Maiu",
		"Junhu",
		"Julhu",
		"Agostu",
		"Setenbru",
		"Otubru",
		"Nuvenbru",
		"Dizenbru"
	],
	"dayPeriods-format-wide-pm": "pm",
	"dateFormat-full": "EEEE, d 'di' MMMM 'di' y",
	"dateFormatItem-Md": "dd/MM",
	"field-era": "Era",
	"dateFormatItem-yM": "MM/y",
	"months-standAlone-wide": [
		"Janeru",
		"Fevereru",
		"Marsu",
		"Abril",
		"Maiu",
		"Junhu",
		"Julhu",
		"Agostu",
		"Setenbru",
		"Otubru",
		"Nuvenbru",
		"Dizenbru"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"Primeru Trimestri",
		"Sigundu Trimestri",
		"Terseru Trimestri",
		"Kuartu Trimestri"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Anu",
	"dateFormatItem-yMMM": "MMM 'di' y",
	"dateFormatItem-yQ": "Q y",
	"field-hour": "Ora",
	"dateFormatItem-MMdd": "dd/MM",
	"months-format-abbr": [
		"Jan",
		"Fev",
		"Mar",
		"Abr",
		"Mai",
		"Jun",
		"Jul",
		"Ago",
		"Set",
		"Otu",
		"Nuv",
		"Diz"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "Oji",
	"field-day-relative+1": "Manha",
	"months-standAlone-abbr": [
		"Jan",
		"Fev",
		"Mar",
		"Abr",
		"Mai",
		"Jun",
		"Jul",
		"Ago",
		"Set",
		"Otu",
		"Nuv",
		"Diz"
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-standAlone-wide": [
		"Primeru Trimestri",
		"Sigundu Trimestri",
		"Terseru Trimestri",
		"Kuartu Trimestri"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"dumingu",
		"sigunda-fera",
		"tersa-fera",
		"kuarta-fera",
		"kinta-fera",
		"sesta-fera",
		"sabadu"
	],
	"dateFormatItem-yyyyMMM": "MMM 'de' yyyy",
	"dateFormatItem-MMMMd": "d 'di' MMMM",
	"dateFormatItem-yyMMM": "MMM yy",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"eraAbbr": [
		"AK",
		"DK"
	],
	"field-minute": "Minutu",
	"field-dayperiod": "am/pm",
	"days-standAlone-abbr": [
		"dum",
		"sig",
		"ter",
		"kua",
		"kin",
		"ses",
		"sab"
	],
	"dateFormatItem-yyMMMd": "d 'de' MMM 'de' yy",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "Onti",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, dd/MM",
	"dateFormatItem-yMMMM": "MMMM 'di' y",
	"field-day": "Dia",
	"days-format-wide": [
		"dumingu",
		"sigunda-fera",
		"tersa-fera",
		"kuarta-fera",
		"kinta-fera",
		"sesta-fera",
		"sabadu"
	],
	"field-zone": "Ora lokal",
	"dateFormatItem-yyyyMM": "MM/yyyy",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dateFormatItem-yyMM": "MM/yy",
	"days-format-abbr": [
		"dum",
		"sig",
		"ter",
		"kua",
		"kin",
		"ses",
		"sab"
	],
	"eraNames": [
		"Antis di Kristu",
		"Dispos di Kristu"
	],
	"days-format-narrow": [
		"d",
		"s",
		"t",
		"k",
		"k",
		"s",
		"s"
	],
	"field-month": "Mes",
	"days-standAlone-narrow": [
		"d",
		"s",
		"t",
		"k",
		"k",
		"s",
		"s"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-HHmm": "HH:mm",
	"dayPeriods-format-wide-am": "am",
	"dateFormatItem-MMMMEd": "E, d 'di' MMMM",
	"dateFormat-short": "d/M/yyyy",
	"field-second": "Sigundu",
	"dateFormatItem-yMMMEd": "E, d 'di' MMM 'di' y",
	"dateFormatItem-Ed": "E, d",
	"field-week": "Simana",
	"dateFormat-medium": "d 'di' MMM 'di' y",
	"dateFormatItem-mmss": "mm:ss"
}
//end v1.x content
);