define(
"dojo/cldr/nls/mk/gregorian", //begin v1.x content
{
	"dateFormatItem-yM": "y-M",
	"field-dayperiod": "претпладне/попладне",
	"dateFormatItem-yQ": "y Q",
	"dayPeriods-format-wide-pm": "попладне",
	"field-minute": "Минута",
	"eraNames": [
		"пр.н.е.",
		"ае."
	],
	"dateFormatItem-MMMEd": "E MMM d",
	"field-day-relative+-1": "Вчера",
	"field-weekday": "Ден во неделата",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-yQQQ": "y QQQ",
	"field-day-relative+-2": "завчера",
	"days-standAlone-wide": [
		"недела",
		"понеделник",
		"вторник",
		"среда",
		"четврток",
		"петок",
		"сабота"
	],
	"dateFormatItem-MMM": "LLL",
	"months-standAlone-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"field-era": "Ера",
	"field-hour": "Час",
	"dayPeriods-format-wide-am": "претпладне",
	"quarters-standAlone-abbr": [
		"јан-мар",
		"апр-јун",
		"јул-сеп",
		"окт-дек"
	],
	"dateFormatItem-y": "y",
	"months-standAlone-abbr": [
		"јан.",
		"фев.",
		"мар.",
		"апр.",
		"мај",
		"јун.",
		"јул.",
		"авг.",
		"септ.",
		"окт.",
		"ноем.",
		"декем."
	],
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-yMMM": "y MMM",
	"field-day-relative+0": "Денес",
	"field-day-relative+1": "Утре",
	"days-standAlone-narrow": [
		"н",
		"п",
		"в",
		"с",
		"ч",
		"п",
		"с"
	],
	"eraAbbr": [
		"пр.н.е.",
		"ае."
	],
	"field-day-relative+2": "задутре",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"dateFormat-long": "dd MMMM y",
	"field-zone": "зона",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormat-medium": "dd.M.yyyy",
	"dateFormatItem-Hms": "HH:mm:ss",
	"quarters-standAlone-wide": [
		"прво тромесечје",
		"второ тромесечје",
		"трето тромесечје",
		"четврто тромесечје"
	],
	"dateFormatItem-yMMMM": "y MMMM",
	"dateFormatItem-ms": "mm:ss",
	"field-year": "година",
	"field-week": "Недела",
	"months-standAlone-wide": [
		"јануари",
		"февруари",
		"март",
		"април",
		"мај",
		"јуни",
		"јули",
		"август",
		"септември",
		"октомври",
		"ноември",
		"декември"
	],
	"dateFormatItem-MMMMEd": "E MMMM d",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-yyQ": "Q yy",
	"months-format-abbr": [
		"јан.",
		"фев.",
		"мар.",
		"апр.",
		"мај",
		"јун.",
		"јул.",
		"авг.",
		"септ.",
		"окт.",
		"ноем.",
		"декем."
	],
	"field-month": "Месец",
	"dateFormatItem-MMMMd": "MMMM d",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"days-format-abbr": [
		"нед.",
		"пон.",
		"вт.",
		"сре.",
		"чет.",
		"пет.",
		"саб."
	],
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormatItem-M": "L",
	"days-format-narrow": [
		"н",
		"п",
		"в",
		"с",
		"ч",
		"п",
		"с"
	],
	"field-second": "Секунда",
	"field-day": "ден",
	"dateFormatItem-MEd": "E, M-d",
	"months-format-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"dateFormatItem-hm": "h:mm a",
	"days-standAlone-abbr": [
		"нед.",
		"пон.",
		"вт.",
		"сре.",
		"чет.",
		"пет.",
		"саб."
	],
	"dateFormat-short": "dd.M.yy",
	"dateFormatItem-Mdd": "dd.M",
	"dateFormatItem-yyyyM": "M.yyyy",
	"dateFormatItem-yMMMEd": "E, y MMM d",
	"dateFormat-full": "EEEE, dd MMMM y",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-yMEd": "E, y-M-d",
	"months-format-wide": [
		"јануари",
		"февруари",
		"март",
		"април",
		"мај",
		"јуни",
		"јули",
		"август",
		"септември",
		"октомври",
		"ноември",
		"декември"
	],
	"dateFormatItem-d": "d",
	"quarters-format-wide": [
		"прво тромесечје",
		"второ тромесечје",
		"трето тромесечје",
		"четврто тромесечје"
	],
	"days-format-wide": [
		"недела",
		"понеделник",
		"вторник",
		"среда",
		"четврток",
		"петок",
		"сабота"
	],
	"eraNarrow": [
		"пр.н.е.",
		"ае."
	]
}
//end v1.x content
);