define(
"dojo/cldr/nls/bn/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"জা",
		"ফে",
		"মা",
		"এ",
		"মে",
		"জুন",
		"জু",
		"আ",
		"সে",
		"অ",
		"ন",
		"ডি"
	],
	"quarters-standAlone-narrow": [
		"১",
		"২",
		"৩",
		"৪"
	],
	"field-weekday": "সপ্তাহের দিন",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-MMMEd": "E d MMM",
	"eraNarrow": [
		"খৃষ্টপূর্ব",
		"খৃষ্টাব্দ"
	],
	"dateFormat-long": "d MMMM, y",
	"months-format-wide": [
		"জানুয়ারী",
		"ফেব্রুয়ারী",
		"মার্চ",
		"এপ্রিল",
		"মে",
		"জুন",
		"জুলাই",
		"আগস্ট",
		"সেপ্টেম্বর",
		"অক্টোবর",
		"নভেম্বর",
		"ডিসেম্বর"
	],
	"dayPeriods-format-wide-pm": "অপরাহ্ণ",
	"dateFormat-full": "EEEE, d MMMM, y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "যুগ",
	"dateFormatItem-yM": "M/yyyy",
	"months-standAlone-wide": [
		"জানুয়ারী",
		"ফেব্রুয়ারী",
		"মার্চ",
		"এপ্রিল",
		"মে",
		"জুন",
		"জুলাই",
		"আগস্ট",
		"সেপ্টেম্বর",
		"অক্টোবর",
		"নভেম্বর",
		"ডিসেম্বর"
	],
	"timeFormat-short": "h:mm a",
	"quarters-format-wide": [
		"প্রথম চতুর্থাংশ",
		"দ্বিতীয় চতুর্থাংশ",
		"তৃতীয় চতুর্থাংশ",
		"চতুর্থ চতুর্থাংশ"
	],
	"timeFormat-long": "h:mm:ss a z",
	"field-year": "বছর",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q y",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-hour": "ঘন্টা",
	"dateFormatItem-MMdd": "dd-MM",
	"months-format-abbr": [
		"জানুয়ারী",
		"ফেব্রুয়ারী",
		"মার্চ",
		"এপ্রিল",
		"মে",
		"জুন",
		"জুলাই",
		"আগস্ট",
		"সেপ্টেম্বর",
		"অক্টোবর",
		"নভেম্বর",
		"ডিসেম্বর"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "h:mm:ss a zzzz",
	"field-day-relative+0": "আজ",
	"field-day-relative+1": "আগামীকাল",
	"field-day-relative+2": "আগামী পরশু",
	"months-standAlone-abbr": [
		"জানুয়ারী",
		"ফেব্রুয়ারী",
		"মার্চ",
		"এপ্রিল",
		"মে",
		"জুন",
		"জুলাই",
		"আগস্ট",
		"সেপ্টেম্বর",
		"অক্টোবর",
		"নভেম্বর",
		"ডিসেম্বর"
	],
	"quarters-format-abbr": [
		"চতুর্থাংশ ১",
		"চতুর্থাংশ ২",
		"চতুর্থাংশ ৩",
		"চতুর্থাংশ ৪"
	],
	"quarters-standAlone-wide": [
		"প্রথম চতুর্থাংশ",
		"দ্বিতীয় চতুর্থাংশ",
		"তৃতীয় চতুর্থাংশ",
		"চতুর্থ চতুর্থাংশ"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"রবিবার",
		"সোমবার",
		"মঙ্গলবার",
		"বুধবার",
		"বৃহষ্পতিবার",
		"শুক্রবার",
		"শনিবার"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"timeFormat-medium": "h:mm:ss a",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"eraAbbr": [
		"খৃষ্টপূর্ব",
		"খৃষ্টাব্দ"
	],
	"field-minute": "মিনিট",
	"field-dayperiod": "পূর্বাহ্ণ/অপরাহ্ণ",
	"days-standAlone-abbr": [
		"রবি",
		"সোম",
		"মঙ্গল",
		"বুধ",
		"বৃহস্পতি",
		"শুক্র",
		"শনি"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "গতকাল",
	"field-day-relative+-2": "গত পরশু",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "দিন",
	"days-format-wide": [
		"রবিবার",
		"সোমবার",
		"মঙ্গলবার",
		"বুধবার",
		"বৃহষ্পতিবার",
		"শুক্রবার",
		"শনিবার"
	],
	"field-zone": "এলাকা",
	"dateFormatItem-yyyyMM": "MM-yyyy",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"জা",
		"ফে",
		"মা",
		"এ",
		"মে",
		"জুন",
		"জু",
		"আ",
		"সে",
		"অ",
		"ন",
		"ডি"
	],
	"field-year-relative+-1": "আগের বছর",
	"field-month-relative+-1": "গত মাস",
	"days-format-abbr": [
		"রবি",
		"সোম",
		"মঙ্গল",
		"বুধ",
		"বৃহস্পতি",
		"শুক্র",
		"শনি"
	],
	"dateFormatItem-yMMMd": "d MMM, y",
	"eraNames": [
		"খৃষ্টপূর্ব",
		"খৃষ্টাব্দ"
	],
	"days-format-narrow": [
		"র",
		"সো",
		"ম",
		"বু",
		"বৃ",
		"শু",
		"শ"
	],
	"field-month": "মাস",
	"days-standAlone-narrow": [
		"র",
		"সো",
		"ম",
		"বু",
		"বৃ",
		"শু",
		"শ"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "পূর্বাহ্ণ",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormat-short": "d/M/yy",
	"field-second": "সেকেন্ড",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"field-month-relative+0": "এই মাস",
	"field-month-relative+1": "পরের মাস",
	"dateFormatItem-Ed": "d E",
	"field-week": "সপ্তাহ",
	"dateFormat-medium": "d MMM, y",
	"field-year-relative+0": "এই বছর",
	"field-week-relative+-1": "গত সপ্তাহ",
	"field-year-relative+1": "পরের বছর",
	"field-week-relative+0": "এই সপ্তাহ",
	"field-week-relative+1": "পরবর্তী সপ্তাহ"
}
//end v1.x content
);