define(
"dojo/cldr/nls/gsw/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-weekday": "Wuchetag",
	"dateFormatItem-yyQQQQ": "QQQQ yy",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, yyyy-M-d",
	"dateFormatItem-MMMEd": "E d. MMM",
	"eraNarrow": [
		"v. Chr.",
		"n. Chr."
	],
	"dateFormat-long": "d. MMMM y",
	"months-format-wide": [
		"Januar",
		"Februar",
		"März",
		"April",
		"Mai",
		"Juni",
		"Juli",
		"Auguscht",
		"Septämber",
		"Oktoober",
		"Novämber",
		"Dezämber"
	],
	"dayPeriods-format-wide-pm": "nam.",
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-yyMMdd": "dd.MM.yy",
	"field-era": "Epoche",
	"dateFormatItem-yM": "yyyy-M",
	"months-standAlone-wide": [
		"Januar",
		"Februar",
		"März",
		"April",
		"Mai",
		"Juni",
		"Juli",
		"Auguscht",
		"Septämber",
		"Oktoober",
		"Novämber",
		"Dezämber"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"1. Quartal",
		"2. Quartal",
		"3. Quartal",
		"4. Quartal"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Jaar",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-hour": "Schtund",
	"dateFormatItem-MMdd": "dd.MM.",
	"months-format-abbr": [
		"Jan",
		"Feb",
		"Mär",
		"Apr",
		"Mai",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Dez"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "hüt",
	"field-day-relative+1": "moorn",
	"field-day-relative+2": "übermoorn",
	"dateFormatItem-H": "H",
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mär",
		"Apr",
		"Mai",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Dez"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-wide": [
		"1. Quartal",
		"2. Quartal",
		"3. Quartal",
		"4. Quartal"
	],
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Sunntig",
		"Määntig",
		"Ziischtig",
		"Mittwuch",
		"Dunschtig",
		"Friitig",
		"Samschtig"
	],
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-yyMMM": "MMM yy",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "H:mm",
	"eraAbbr": [
		"v. Chr.",
		"n. Chr."
	],
	"field-minute": "Minuute",
	"field-dayperiod": "Tageshälfti",
	"days-standAlone-abbr": [
		"Su.",
		"Mä.",
		"Zi.",
		"Mi.",
		"Du.",
		"Fr.",
		"Sa."
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+-1": "geschter",
	"field-day-relative+-2": "vorgeschter",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "Tag",
	"days-format-wide": [
		"Sunntig",
		"Määntig",
		"Ziischtig",
		"Mittwuch",
		"Dunschtig",
		"Friitig",
		"Samschtig"
	],
	"field-zone": "Zone",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"dateFormatItem-yyMM": "MM.yy",
	"days-format-abbr": [
		"Su.",
		"Mä.",
		"Zi.",
		"Mi.",
		"Du.",
		"Fr.",
		"Sa."
	],
	"eraNames": [
		"v. Chr.",
		"n. Chr."
	],
	"days-format-narrow": [
		"S",
		"M",
		"D",
		"M",
		"D",
		"F",
		"S"
	],
	"field-month": "Monet",
	"days-standAlone-narrow": [
		"S",
		"M",
		"D",
		"M",
		"D",
		"F",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-HHmm": "HH:mm",
	"dayPeriods-format-wide-am": "vorm.",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMdd": "dd. MMMM",
	"dateFormat-short": "dd.MM.yy",
	"dateFormatItem-MMd": "d.MM.",
	"field-second": "Sekunde",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateFormatItem-Ed": "E d.",
	"field-week": "Wuche",
	"dateFormat-medium": "dd.MM.yyyy",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-yyyy": "y"
}
//end v1.x content
);