define(
"dojo/cldr/nls/ee/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"d",
		"d",
		"t",
		"a",
		"d",
		"m",
		"s",
		"d",
		"a",
		"k",
		"a",
		"d"
	],
	"field-weekday": "kɔsiɖa me ŋkeke",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, M/d/y",
	"dateFormatItem-MMMEd": "E, MMM d",
	"eraNarrow": [
		"hY",
		"Yŋ"
	],
	"dayPeriods-format-wide-earlyMorning": "fɔŋli",
	"dayPeriods-format-wide-morning": "ŋdi",
	"dateFormat-long": "d MMMM y",
	"months-format-wide": [
		"dzove",
		"dzodze",
		"tedoxe",
		"afɔfĩe",
		"dama",
		"masa",
		"siamlɔm",
		"deasiamime",
		"anyɔnyɔ",
		"kele",
		"adeɛmekpɔxe",
		"dzome"
	],
	"dayPeriods-format-wide-evening": "fiẽ",
	"dateTimeFormat-medium": "{0} {1}",
	"dayPeriods-format-wide-pm": "ɣetrɔ",
	"dateFormat-full": "EEEE, d MMMM y",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "ŋɔli",
	"dateFormatItem-yM": "M/y",
	"months-standAlone-wide": [
		"dzove",
		"dzodze",
		"tedoxe",
		"afɔfĩe",
		"dama",
		"masa",
		"siamlɔm",
		"deasiamime",
		"anyɔnyɔ",
		"kele",
		"adeɛmekpɔxe",
		"dzome"
	],
	"timeFormat-short": "a h:mm",
	"quarters-format-wide": [
		"memama ene ƒe akpa gbãtɔ",
		"memama ene ƒe akpa evelia",
		"memama ene ƒe akpa etɔ̃lia",
		"memama ene ƒe akpa enelia"
	],
	"timeFormat-long": "a h:mm:ss z",
	"field-year": "ƒe",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q y",
	"field-hour": "gaƒoƒo",
	"months-format-abbr": [
		"dzv",
		"dzd",
		"ted",
		"afɔ",
		"dam",
		"mas",
		"sia",
		"dea",
		"any",
		"kel",
		"ade",
		"dzm"
	],
	"timeFormat-full": "a h:mm:ss zzzz",
	"dayPeriods-format-wide-earlyAfternoon": "ŋdɔ",
	"field-day-relative+0": "egbe",
	"field-day-relative+1": "etsɔ si gbɔna",
	"field-day-relative+2": "nyitsɔ si gbɔna",
	"months-standAlone-abbr": [
		"dzv",
		"dzd",
		"ted",
		"afɔ",
		"dam",
		"mas",
		"sia",
		"dea",
		"any",
		"kel",
		"ade",
		"dzm"
	],
	"quarters-format-abbr": [
		"q1",
		"q2",
		"q3",
		"q4"
	],
	"quarters-standAlone-wide": [
		"memama ene ƒe akpa gbãtɔ",
		"memama ene ƒe akpa evelia",
		"memama ene ƒe akpa etɔ̃lia",
		"memama ene ƒe akpa enelia"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"kɔsiɖa",
		"dzoɖa",
		"blaɖa",
		"kuɖa",
		"yawoɖa",
		"fiɖa",
		"memleɖa"
	],
	"dateFormatItem-MMMMd": "MMMM d",
	"timeFormat-medium": "a h:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"q1",
		"q2",
		"q3",
		"q4"
	],
	"eraAbbr": [
		"hY",
		"Yŋ"
	],
	"field-minute": "Mintigaƒoƒo",
	"field-dayperiod": "ŋkekea me",
	"days-standAlone-abbr": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"dayPeriods-format-wide-night": "zã",
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "etsɔ si va yi",
	"dateFormatItem-h": "a h",
	"dateTimeFormat-long": "{0} {1}",
	"field-day-relative+-2": "nyitsɔ",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MEd": "E, M/d",
	"dateTimeFormat-full": "{0} {1}",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "ŋkeke",
	"days-format-wide": [
		"kɔsiɖa",
		"dzoɖa",
		"blaɖa",
		"kuɖa",
		"yawoɖa",
		"fiɖa",
		"memleɖa"
	],
	"field-zone": "nutomegaƒoƒome",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"d",
		"d",
		"t",
		"a",
		"d",
		"m",
		"s",
		"d",
		"a",
		"k",
		"a",
		"d"
	],
	"dateFormatItem-hm": "h:mm a",
	"days-format-abbr": [
		"kɔs",
		"dzo",
		"bla",
		"kuɖ",
		"yaw",
		"fiɖ",
		"mem"
	],
	"dateFormatItem-yMMMd": "d MMM y",
	"eraNames": [
		"Hafi Yesu Va Do ŋgɔ",
		"Yesu Ŋɔli"
	],
	"days-format-narrow": [
		"k",
		"d",
		"b",
		"k",
		"y",
		"f",
		"m"
	],
	"field-month": "Xleti",
	"days-standAlone-narrow": [
		"k",
		"d",
		"b",
		"k",
		"y",
		"f",
		"m"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "ŋdi",
	"dateFormatItem-MMMMEd": "E, MMMM d",
	"dateFormat-short": "dd/MM/yyyy",
	"dayPeriods-format-wide-afternoon": "ɣetrɔ",
	"field-second": "sekend",
	"dateFormatItem-yMMMEd": "E, MMM d, y",
	"dateFormatItem-Ed": "E d",
	"field-week": "kɔsiɖa ɖeka",
	"dateFormat-medium": "d MMM y",
	"dateTimeFormat-short": "{0} {1}",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hms": "a h:mm:ss"
}
//end v1.x content
);