define(
"dojo/cldr/nls/gl/gregorian", //begin v1.x content
{
	"months-format-narrow": [
		"X",
		"F",
		"M",
		"A",
		"M",
		"X",
		"X",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-weekday": "Día da semana",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yMEd": "E, d-M-yyyy",
	"dateFormatItem-MMMEd": "E d MMM",
	"eraNarrow": [
		"a.C.",
		"d.C."
	],
	"dateFormat-long": "dd MMMM y",
	"months-format-wide": [
		"Xaneiro",
		"Febreiro",
		"Marzo",
		"Abril",
		"Maio",
		"Xuño",
		"Xullo",
		"Agosto",
		"Setembro",
		"Outubro",
		"Novembro",
		"Decembro"
	],
	"dayPeriods-format-wide-pm": "p.m.",
	"dateFormat-full": "EEEE dd MMMM y",
	"dateFormatItem-Md": "d-M",
	"dayPeriods-format-abbr-am": "a.m.",
	"dateFormatItem-yMd": "d/M/y",
	"field-era": "Era",
	"dateFormatItem-yM": "M-yyyy",
	"months-standAlone-wide": [
		"Xaneiro",
		"Febreiro",
		"Marzo",
		"Abril",
		"Maio",
		"Xuño",
		"Xullo",
		"Agosto",
		"Setembro",
		"Outubro",
		"Novembro",
		"Decembro"
	],
	"timeFormat-short": "HH:mm",
	"quarters-format-wide": [
		"1o trimestre",
		"2o trimestre",
		"3o trimestre",
		"4o trimestre"
	],
	"timeFormat-long": "HH:mm:ss z",
	"field-year": "Ano",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yQ": "Q yyyy",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-hour": "Hora",
	"dateFormatItem-MMdd": "dd/MM",
	"months-format-abbr": [
		"Xan",
		"Feb",
		"Mar",
		"Abr",
		"Mai",
		"Xuñ",
		"Xul",
		"Ago",
		"Set",
		"Out",
		"Nov",
		"Dec"
	],
	"dateFormatItem-yyQ": "Q yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"field-day-relative+0": "hoxe",
	"field-day-relative+1": "mañá",
	"field-day-relative+2": "pasadomañá",
	"months-standAlone-abbr": [
		"Xan",
		"Feb",
		"Mar",
		"Abr",
		"Mai",
		"Xuñ",
		"Xul",
		"Ago",
		"Set",
		"Out",
		"Nov",
		"Dec"
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-standAlone-wide": [
		"1o trimestre",
		"2o trimestre",
		"3o trimestre",
		"4o trimestre"
	],
	"dateFormatItem-M": "L",
	"days-standAlone-wide": [
		"Domingo",
		"Luns",
		"Martes",
		"Mércores",
		"Xoves",
		"Venres",
		"Sábado"
	],
	"dateFormatItem-MMMMd": "d MMMM",
	"timeFormat-medium": "HH:mm:ss",
	"dateFormatItem-Hm": "HH:mm",
	"quarters-standAlone-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"eraAbbr": [
		"a.C.",
		"d.C."
	],
	"field-minute": "Minuto",
	"field-dayperiod": "a.m./p.m.",
	"days-standAlone-abbr": [
		"Dom",
		"Lun",
		"Mar",
		"Mér",
		"Xov",
		"Ven",
		"Sáb"
	],
	"dateFormatItem-d": "d",
	"dateFormatItem-ms": "mm:ss",
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"field-day-relative+-1": "onte",
	"dayPeriods-format-narrow-am": "a",
	"field-day-relative+-2": "antonte",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MEd": "E, d-M",
	"dateFormatItem-yMMMM": "MMMM y",
	"field-day": "Día",
	"days-format-wide": [
		"Domingo",
		"Luns",
		"Martes",
		"Mércores",
		"Xoves",
		"Venres",
		"Sábado"
	],
	"field-zone": "Fuso horario",
	"dateFormatItem-y": "y",
	"months-standAlone-narrow": [
		"X",
		"F",
		"M",
		"A",
		"M",
		"X",
		"X",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"field-year-relative+-1": "Ano pasado",
	"field-month-relative+-1": "Mes pasado",
	"dateFormatItem-yyMM": "MM/yy",
	"dayPeriods-format-abbr-pm": "p.m.",
	"days-format-abbr": [
		"Dom",
		"Lun",
		"Mar",
		"Mér",
		"Xov",
		"Ven",
		"Sáb"
	],
	"dateFormatItem-yMMMd": "d MMM, y",
	"eraNames": [
		"antes de Cristo",
		"despois de Cristo"
	],
	"days-format-narrow": [
		"D",
		"L",
		"M",
		"M",
		"X",
		"V",
		"S"
	],
	"field-month": "Mes",
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"X",
		"V",
		"S"
	],
	"dateFormatItem-MMM": "LLL",
	"dayPeriods-format-wide-am": "a.m.",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMMdd": "dd MMMM",
	"dateFormat-short": "dd/MM/yy",
	"field-second": "Segundo",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"field-month-relative+0": "Este mes",
	"field-month-relative+1": "Mes seguinte",
	"dateFormatItem-Ed": "E d",
	"field-week": "Semana",
	"dateFormat-medium": "d MMM, y",
	"field-year-relative+0": "Este ano",
	"field-week-relative+-1": "Semana pasada",
	"field-year-relative+1": "Seguinte ano",
	"dayPeriods-format-narrow-pm": "p",
	"field-week-relative+0": "Esta semana",
	"field-week-relative+1": "Semana seguinte"
}
//end v1.x content
);